name: adag
description: Aplicación Destinada al Desarrollo Gastronómico

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^1.10.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_crema.png
    - assets/images/logo_naranja.png
    - assets/images/nomades.png
    - assets/images/bocatto.png
    - assets/images/Pizza40.png
    - assets/images/mendieta.png
    - assets/images/the_rox.png
    - assets/images/Holy.png
